### ISSUE TITLE
App in other store

### ISSUE THREAD

**Issue by sguinetti** [fastogt/fastotvlite_mobile#6]
Greetings. I would like to know if it is possible to share this Android app to another store like IzzyOnDroid as an alternative to Play Store. If so, Is possible to upload the apk (build) on the Release page of this repository? Thank you.

Link about this app in IzzyOnDroid: https://gitlab.com/IzzyOnDroid/repo/-/issues/152

**Comment by sguinetti** [comment]
I saw what happened, thanks for agreeing to include the app in IzzyOnDroid.

**Comment by sguinetti** [comment]
Hello @topilski Just a reminder, There is a new update but the apk is not published in Github's Release section. I would appreciate if you could post again.

**Comment by IzzySoft** [comment]
I assume the app has gone proprietary then, @topilski / @sguinetti ? No new release here since 2/2021 (v1.13.4) – while PlayStore had multiple updates since, and currently is at v1.9.7.

As without APKs we can not update the listing at IzzyOnDroid, and moreover the source code for newer releases is not available here: shall we rather remove the outdated version at our end? Or did the repo move elsewhere? With the website link given in the Readme redirecting to some job portal, I'm quite a bit confused here…

**Comment by sguinetti** [comment]
I would be in favor of removing it. It seems to be focused on a different area than the end user, and leaving it in the store will only make it prone to vulnerabilities.

**Comment by IzzySoft** [comment]
OK, done – effective with the next sync.
